### ISSUE TITLE
The automation never gets executed

### ISSUE THREAD

**Issue by mkamrani** [dotenx/dotenx#86]
Pipeline yaml:

```yaml
name: tweet to sendgrid
manifest:
  tasks:
    sendgrid:
      type: Send email
      body:
        sender: <email>
        target: <another email>
        text:
          key: text
          source: trigger
      description: description
      integration: sendgrid
      metadata:
        service: sendGrid
        type: Send email
        fields:
        - key: sender
          type: text
          description: ""
        - key: target
          type: text
          description: ""
        - key: text
          type: text
          description: ""
        image: awrmin/sendemail
        integrations:
        - sendGrid
        author: Armingodiz
        icon: https://sendgrid.com/wp-content/themes/sgdotcom/pages/resource/brand/2016/SendGrid-Logomark.png
        node_color: '#1A82e2'
        description: Sends email using send grid
        outputs: []
  triggers:
    trigger:
      name: trigger
      accountid: <accountid>
      type: Twitter new tweet
      endpoint: 8006cfa2-a45f-43d6-9fd7-29b9bbc6b3f7
      pipeline: tweet to sendgrid
      integration: mytwitter
      credentials:
        passed_seconds: "20000"
        username: MohsenKamranii
      metadata:
        service: twitter
        type: Twitter new tweet
        integrations:
        - twitter
        image: hojjat12/twitter-new-tweet:latest
        credentials:
        - key: username
          type: text
          description: the username of account that you want to check for new tweets
        - key: passed_seconds
          type: text
          description: passed seconds from creation time of tweet
        outputs:
        - key: created_at
          type: text
          description: when the last tweet was published
        - key: text
          type: text
          description: text of the last tweet
        author: Hojjat-1
        icon: https://cdn-icons-png.flaticon.com/512/3128/3128310.png
        node_color: '#00acee'
        description: Checks if there is a new tweet or reply(sent before given number
          of seconds), tiggers a specefic pipeline
endpoint: 8006cfa2-a45f-43d6-9fd7-29b9bbc6b3f7
is_active: false
```
